on:
  push:
    tags:
      - 'eth-connector-v[0-9]+.[0-9]+.[0-9]+*'
  
  workflow_dispatch:

name: Update Contract
jobs:
  update-contract:
    runs-on: ubuntu-latest
    name: Update Contract
    permissions:
      contents: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        
      - name: Install cargo-near
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh

      - name: Build NEAR contract
        run: |
          make build-migration
          make build
        timeout-minutes: 60

      - name: Archive built WASM files
        env:
          RAW_TAG: ${{ github.ref_name }}
        run: |
          SAFE_TAG="${RAW_TAG//./-}"
          ZIP_NAME="${SAFE_TAG}.zip"
          mkdir -p artifacts
          find ./bin -name "*.wasm" -exec cp {} artifacts/ \;
          zip -j "$ZIP_NAME" artifacts/*
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: "*.zip"
